### ISSUE TITLE
Relax rack version requirements

### ISSUE THREAD

**Issue by oneiros** [nomadium/linzer#2]
Hi and thank you for this excellent looking gem!

We at Mastodon are currently evaluating adding HTTP message signature support using linzer.

Sadly, we are stuck with `rack` version 2 for the time being. I had a quick look and the linzer test suite passes just fine with rack `2.2.10`.

Would you consider relaxing the version requirement for `rack`?

**Comment by nomadium** [comment]
Sorry for the delay taking a look at this PR. I'll get back to this later today or tomorrow.
